# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "93ae784931a0ad86103cbaccf58b5d4e"
name = "my-app"
handle = "my-app-1315"
application_url = "https://forces-believes-israeli-pc.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "iframeappatharva.myshopify.com"
include_config_on_deploy = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products"

[auth]
redirect_urls = [
  "https://forces-believes-israeli-pc.trycloudflare.com/auth/callback",
  "https://forces-believes-israeli-pc.trycloudflare.com/auth/shopify/callback",
  "https://forces-believes-israeli-pc.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-04"

[pos]
embedded = false
